//@version=4
study("Donchain Channels + SSL channel + 50/200 EMA", overlay=true)

length = input(20, minval=1)
lower = lowest(length)
upper = highest(length)
basis = avg(upper, lower)
plot(basis, "Basis", color=#FF6A00)
u = plot(upper, "Upper", color=#0094FF)
l = plot(lower, "Lower", color=#0094FF)
fill(u, l, color=#0094FF, transp=95, title="Background")

//ssl channel
period=input(title="SSL Period", defval=10)
len=input(title="SSL length", defval=10)
smaHigh=sma(high, len)
smaLow=sma(low, len)
float Hlv = na
Hlv := close > smaHigh ? 1 : close < smaLow ? -1 : Hlv[1]
sslDown = Hlv < 0 ? smaHigh: smaLow
sslUp   = Hlv < 0 ? smaLow : smaHigh

plot(sslDown, title="SSL Down", linewidth=1, color=color.red)
plot(sslUp, title="SSL UP", linewidth=1, color=color.lime)

ema50=input(title="50 EMA", defval=50)
plot(ema(close,ema50), title="50 EMA" ,color = color.purple)
ema200=input(title="200 EMA", defval=200)
plot(ema(close,ema200), title="200 EMA" ,color = color.fuchsia)
