//@version=4
study(title="2 Stochastic + RSI", shorttitle="2Stoch+rsi", format=format.price, precision=2, resolution="")

var lw = 2
var tlw = 3

// show
show1 = input(title="Show Stoch 1", type=input.bool, defval=true)
show2 = input(title="Show Stoch 2", type=input.bool, defval=true)

// stoch 1
periodK1 = input(14, title="K 1", minval=1)
periodD1 = input(3, title="D 1", minval=1)
smoothK1 = input(3, title="Smooth 1", minval=1)
k1 = sma(stoch(close, high, low, periodK1), smoothK1)
d1 = sma(k1, periodD1)

// stoch 2
periodK2 = input(4, title="K2", minval=1)
periodD2 = input(3, title="D2", minval=1)
smoothK2 = input(3, title="Smooth2", minval=1)
k2 = sma(stoch(close, high, low, periodK2), smoothK2)
d2 = sma(k2, periodD2)

// draw
plot(k1, title="%K1", color=#0094FF, linewidth=1, transp=show1 ? 0 : 100)
plot(d1, title="%D1", color=#FF6A00, linewidth=1, transp=show1 ? 0 : 100)
lw1 = k1 <= 20 or k1 >= 80 ? tlw : lw
plot(crossover(k1, d1) ? k1 : na, title="Stoch 1 crossover", style=plot.style_cross, color=#0094FF, linewidth=lw, transp=show1 ? 0 : 100)
plot(crossunder(k1, d1) ? k1 : na, title="Stoch 1 crossunder", style=plot.style_cross, color=#FF6A00, linewidth=lw, transp=show1 ? 0 : 100)

plot(k2, title="%K2", color=#6EFF0D, linewidth=1, transp=show2 ? 0 : 100)
plot(d2, title="%D2", color=#FF0D6E, linewidth=1, transp=show2 ? 0 : 100)
plot(crossover(k2, d2) ? k2 : na, title="Stoch 2 crossover", style=plot.style_cross, color=#6EFF0D, linewidth=lw, transp=show2 ? 0 : 100)
plot(crossunder(k2, d2) ? k2 : na, title="Stoch 2 crossunder", style=plot.style_cross, color=#FF0D6E, linewidth=lw, transp=show2 ? 0 : 100)

// band
h0 = hline(80, "Stoch Upper Band", color=#606060)
h1 = hline(20, "Stoch Lower Band", color=#606060)
fill(h0, h1, color=#9915FF, transp=80, title="Stoch Background")

// rsi
rsi_len = input(4, minval=1, title="RSI Length")
rsi_src = input(close, "Source", type = input.source)
rsi_up = rma(max(change(rsi_src), 0), rsi_len)
rsi_down = rma(-min(change(rsi_src), 0), rsi_len)
rsi_rsi = rsi_down == 0 ? 100 : rsi_up == 0 ? 0 : 100 - (100 / (1 + rsi_up / rsi_down))
plot(rsi_rsi, "RSI", color=color.white, linewidth=2, transp=80)
rsi_band1 = hline(70, "RSI Upper Band", color=#C0C0C0)
rsi_band0 = hline(30, "RSI Lower Band", color=#C0C0C0)
fill(rsi_band1, rsi_band0, color=#9915FF, transp=100, title="RSI Background")
